services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/prod/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "8081:15672"
    volumes:
      - ./data/prod/rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env
  generator:
    build:
      dockerfile: generator/Dockerfile
    env_file:
      - .env
    environment:
      - RABBIT_URL=amqp://rabbit:rabbit@rabbitmq:5672/