apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evaluation
  name: evaluation
  namespace: dataluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
        - name: evaluation
          image: ghcr.io/checky2010/studies.cnd/evaluation:main
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq-user
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_QUEUE
              value: DatapointGenerator
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-user
            - name: POSTGRES_DATABASE
              value: evaluation
      restartPolicy: Always