apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator
  name: generator
  namespace: dataluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: ghcr.io/checky2010/studies.cnd/generator:main
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq-user
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: RABBITMQ_QUEUE
              value: DatapointGenerator
      restartPolicy: Always