apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator
  name: generator
  namespace: dataluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: asd # TODO
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: rabbitmq-user
            - name: RABBITMQ_HOST
              value: rabbitmq.dataluation.svc.cluster.local
            - name: RABBITMQ_QUEUE
              value: DatapointGenerator
      restartPolicy: Always