apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: rabbitmq
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: management
  selector:
    app: rabbitmq
  type: ClusterIP