apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    type: local
  namespace: dataluation
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/case/k8s/rabbitmq
  claimRef:
    name: rabbitmq-pvc
    namespace: dataluation